/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeMX
 * @brief     Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
// 弱符号声明的字符输入输出函数（可由用户重定义，如重定向到串口）
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


// 环境变量（空，嵌入式系统通常不需要）
char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
// 初始化监视器句柄（空实现，用于兼容调试器 semihosting）
void initialise_monitor_handles()
{
}

// 返回当前进程ID（嵌入式裸机固定返回1）
int _getpid(void)
{
  return 1;
}

// 发送信号给进程（嵌入式不支持，返回错误）
int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

// 进程退出（调用_kill后死循环）
void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* 确保停在这里 */
}

// 读取文件（弱符号，通过__io_getchar逐字节读取，可用于串口输入重定向）
__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

// 写入文件（弱符号，通过__io_putchar逐字节输出，可用于串口输出重定向/printf重定向）
__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

// 关闭文件（不支持，返回-1）
int _close(int file)
{
  (void)file;
  return -1;
}

// 获取文件状态（所有文件视为字符设备）
int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

// 判断文件描述符是否为终端（嵌入式固定返回1=是终端）
int _isatty(int file)
{
  (void)file;
  return 1;
}

// 文件寻址（不支持，返回0）
int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

// 打开文件（不支持，始终失败）
int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  return -1;
}

// 等待子进程（不支持）
int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

// 删除文件（不支持）
int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

// 获取进程时间（不支持）
clock_t _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

// 获取文件信息（不支持）
int _stat(const char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

// --- Picolibc Specific Section ---
#if defined(__PICOLIBC__)

/**
 * @brief Picolibc helper function to output a character to a FILE stream.
 *        This redirects the output to the low-level __io_putchar function.
 * @param c Character to write.
 * @param file FILE stream pointer (ignored).
 * @retval int The character written.
 */
static int starm_putc(char c, FILE *file)
{
	(void) file;
  __io_putchar(c);
	return c;
}

/**
 * @brief Picolibc helper function to input a character from a FILE stream.
 *        This redirects the input from the low-level __io_getchar function.
 * @param file FILE stream pointer (ignored).
 * @retval int The character read, cast to an unsigned char then int.
 */
static int starm_getc(FILE *file)
{
	unsigned char c;
	(void) file;
  c = __io_getchar();
	return c;
}

// Define and initialize the standard I/O streams for Picolibc.
// FDEV_SETUP_STREAM connects the starm_putc and starm_getc helper functions to a FILE structure.
// _FDEV_SETUP_RW indicates the stream is for reading and writing.
static FILE __stdio = FDEV_SETUP_STREAM(starm_putc,
					starm_getc,
					NULL,
					_FDEV_SETUP_RW);

// Assign the standard stream pointers (stdin, stdout, stderr) to the initialized stream.
// Picolibc uses these pointers for standard I/O operations (printf, scanf, etc.).
FILE *const stdin = &__stdio;
__strong_reference(stdin, stdout);
__strong_reference(stdin, stderr);

// Create strong aliases mapping standard C library function names (without underscore)
// to the implemented system call stubs (with underscore). Picolibc uses these
// standard names internally, so this linking is required.
__strong_reference(_read, read);
__strong_reference(_write, write);
__strong_reference(_times, times);
__strong_reference(_execve, execve);
__strong_reference(_fork, fork);
__strong_reference(_link, link);
__strong_reference(_unlink, unlink);
__strong_reference(_stat, stat);
__strong_reference(_wait, wait);
__strong_reference(_open, open);
__strong_reference(_close, close);
__strong_reference(_lseek, lseek);
__strong_reference(_isatty, isatty);
__strong_reference(_fstat, fstat);
__strong_reference(_exit, exit);
__strong_reference(_kill, kill);
__strong_reference(_getpid, getpid);

#endif //__PICOLIBC__
