/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeMX
 * @brief     System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the Newlib or Picolibc libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <stddef.h>

/**
 * 当前堆使用的高水位标记指针
 * 堆从 _end（链接脚本中定义的BSS段末尾）开始向上增长
 * MSP栈从 _estack 向下增长，两者之间需要保留 _Min_Stack_Size 的间距
 */
static uint8_t *__sbrk_heap_end = NULL;

/**
 * @brief _sbrk() 为 newlib 堆分配内存，被 malloc/free 等 C 库函数调用
 *
 * @verbatim
 * ############################################################################
 * #  .data  #  .bss  #       newlib heap       #          MSP stack          #
 * #         #        #                         #  由 _Min_Stack_Size 保留   #
 * ############################################################################
 * ^-- RAM起始              ^-- _end                             _estack, RAM末尾 --^
 * @endverbatim
 *
 * 分配从链接符号 '_end' 开始
 * 链接符号 '_Min_Stack_Size' 为 MSP 栈保留内存空间
 * 链接符号 '_estack' 为 RAM 末尾地址
 * 注意：如果运行时 MSP 栈增长超过预留大小，请增大 '_Min_Stack_Size'
 *
 * @param incr 请求分配的内存大小（字节）
 * @return 分配的内存指针，失败返回 (void*)-1
 */
void *_sbrk(ptrdiff_t incr)
{
  extern uint8_t _end;              /* 链接脚本中定义的符号：BSS段末尾 = 堆起始地址 */
  extern uint8_t _estack;           /* 链接脚本中定义的符号：栈顶 = RAM末尾 */
  extern uint32_t _Min_Stack_Size;  /* 链接脚本中定义的符号：最小栈空间（字节） */
  const uint32_t stack_limit = (uint32_t)&_estack - (uint32_t)&_Min_Stack_Size;  // 栈底边界
  const uint8_t *max_heap = (uint8_t *)stack_limit;   // 堆的最大允许地址
  uint8_t *prev_heap_end;

  /* 首次调用时初始化堆起始地址 */
  if (NULL == __sbrk_heap_end)
  {
    __sbrk_heap_end = &_end;
  }

  /* 防止堆增长侵入MSP栈保留空间 */
  if (__sbrk_heap_end + incr > max_heap)
  {
    errno = ENOMEM;        // 内存不足
    return (void *)-1;      // 返回失败
  }

  prev_heap_end = __sbrk_heap_end;
  __sbrk_heap_end += incr;  // 堆指针上移

  return (void *)prev_heap_end;
}

#if defined(__PICOLIBC__)
  // Picolibc 库期望 syscall 不带前导下划线
  // 此处创建强别名，使 sbrk() 调用解析到 _sbrk() 实现
  __strong_reference(_sbrk, sbrk);
#endif
